### ISSUE TITLE
emacs-mac 7.9 fails to install on Mojave 10.14.6

### ISSUE THREAD

**Issue by ecssvma** [railwaycat/homebrew-emacsmacport#190]
emacs-mac install fine on my Catalina Mac mini but fails on my Mojave MacBook Pro (similar brew configuration) with:
==> Upgrading 1 outdated package:
railwaycat/emacsmacport/emacs-mac emacs-26.3-z-mac-7.8 -> emacs-26.3-z-mac-7.9
==> Upgrading railwaycat/emacsmacport/emacs-mac emacs-26.3-z-mac-7.8 -
==> Downloading https://bitbucket.org/mituharu/emacs-mac/get/emacs-26.3-mac-7.9.
Already downloaded: /Users/ecssvma/Library/Caches/Homebrew/downloads/d40a03147c5fc96cf9881acda3a44da8484e8897f1a9917085679a6de7276535--mituharu-emacs-mac-26c8fd9920db.tar.gz
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodi
==> make
Last 15 lines from /Users/ecssvma/Library/Logs/Homebrew/emacs-mac/03.make:
  CC       fringe.o
  CC       image.o
  CC       macappkit.o
  CC       macfont.o
  CC       terminfo.o
  CC       lastfile.o
macappkit.m:2414:42: error: use of undeclared identifier 'NSAppKitVersionNumber10_14'
  if (!(floor (NSAppKitVersionNumber) <= NSAppKitVersionNumber10_14))
                                         ^
macappkit.m:3940:46: error: use of undeclared identifier 'NSAppKitVersionNumber10_14'
      && (!(floor (NSAppKitVersionNumber) <= NSAppKitVersionNumber10_14)
                                             ^
2 errors generated.
make[1]: *** [macappkit.o] Error 1
make: *** [src] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/railwaycat/homebrew-emacsmacport/issues

These open issues may also help:
emacs-mac.rb: Use `each_key` instead of `keys.each` https://github.com/railwaycat/homebrew-emacsmacport/pull/117
Update to emacs-25.2-rc2-mac-6.2 https://github.com/railwaycat/homebrew-emacsmacport/pull/93
Fullscreen on emacs-25.1-rc1-mac-5.90 https://github.com/railwaycat/homebrew-emacsmacport/issues/68
Error: /Library/Caches/Homebrew/Formula/emacs-mac.rb:4 https://github.com/railwaycat/homebrew-emacsmacport/issues/39
emacs-mac failed to build on 10.10.2 https://github.com/railwaycat/homebrew-emacsmacport/issues/17

==> Checking for dependents of upgraded formulae...
==> No dependents found!
Warning: Skipping railwaycat/emacsmacport/emacs-mac: most recent version emacs-26.3-z-mac-7.9 not installed
Your system is ready to brew.

**Comment by dotemacs** [comment]
I just compiled it on Mojave 10.14.6 macbook, no issues.

My situation was the same as yours: emacs-mac emacs-26.3-z-mac-7.8 -> emacs-26.3-z-mac-7.9

**Comment by ecssvma** [comment]
Thanks.  I tried on a high sierra machine without any problems so I
re-installed brew in various ways to no avail

Finally, reinstalling the command-line tools seemed to fix the problem
(xcode-select -r was not enough).

Den fre 3 apr. 2020 kl 16:26 skrev Александар Симић <
notifications@github.com>:
