### ISSUE TITLE
27.1 fails to compile on 10.14.6

### ISSUE THREAD

**Issue by bnomis** [railwaycat/homebrew-emacsmacport#224]
Compiling gives the errors message below

```shell
==> make
Last 15 lines from /Users/simonb/Library/Logs/Homebrew/emacs-mac/03.make:
../build-aux/install-sh -c -d ../etc
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../lisp update-subdirs
cp -f temacs bootstrap-emacs
rm -f bootstrap-emacs.pdmp
./temacs --batch  -l loadup --temacs=pbootstrap
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /private/tmp/emacs-mac-20200914-10356-1u2let6/mituharu-emacs-mac-dfb5869abf8f/src/./temacs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
  Referenced from: /private/tmp/emacs-mac-20200914-10356-1u2let6/mituharu-emacs-mac-dfb5869abf8f/src/./temacs
  Expected in: /usr/lib/libSystem.B.dylib

make[1]: *** [bootstrap-emacs.pdmp] Abort trap: 6
make: *** [src] Error 2
```

**Comment by railwaycat** [comment]
Since it has been several major versions after the issue be created, I will close this issue for now and please feel free to reopen it or open new one if same issue occurs.
