### ISSUE TITLE
Trouble installing emacs-25.3-mac-6.8

### ISSUE THREAD

**Issue by ViktorHaag** [railwaycat/homebrew-emacsmacport#109]
Running on OSX 10.12.6
xcode-select version: 2347, command line tools installed
XCode 9.0
upgrading from emacs-25.3-mac-6.7

From a clean install (i.e. removed previous emacs-mac package after initially unable to upgrade).

The issue seems to be permission issue of some sort with `../build-aux/install-sh`

Here's the output from brew:
```
>> brew install emacs-mac --with-xml2 --with-ctags --with-spacemacs-icon

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
app-engine-java             grafana                     osmfilter                   prometheus

==> Installing emacs-mac from railwaycat/emacsmacport
==> Downloading https://bitbucket.org/mituharu/emacs-mac/get/emacs-25.3-mac-6.8.tar.bz2
Already downloaded: /Users/vhaag/Library/Caches/Homebrew/emacs-mac-emacs-25.3-mac-6.8.tar.bz2
==> Downloading https://github.com/nashamri/spacemacs-logo/blob/master/spacemacs.icns?raw=true
Already downloaded: /Users/vhaag/Library/Caches/Homebrew/emacs-mac--spacemacs-icon-emacs-25.3-mac-6.8.icns
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/
==> make
Last 15 lines from /Users/vhaag/Library/Logs/Homebrew/emacs-mac/03.make:
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/French.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/German.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/Italian.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/Japanese.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/Spanish.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/ar.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/ca.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/cs.lproj
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/da.lproj
make[2]: ../build-aux/install-sh: Permission denied
../build-aux/install-sh -c -d Emacs.app/Contents/Resources/el.lproj
make[2]: *** [Emacs.app/Contents/Resources/da.lproj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [macosx-app] Error 2
make: *** [src] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/railwaycat/homebrew-emacsmacport/issues

These open issues may also help:
Trouble installing emacs-25.3-mac-6.7 https://github.com/railwaycat/homebrew-emacsmacport/issues/108
Update to emacs-25.2-rc2-mac-6.2 https://github.com/railwaycat/homebrew-emacsmacport/pull/93
Fullscreen on emacs-25.1-rc1-mac-5.90 https://github.com/railwaycat/homebrew-emacsmacport/issues/68
emacs-mac does not install from HEAD - make info problem https://github.com/railwaycat/homebrew-emacsmacport/issues/89
Error: /Library/Caches/Homebrew/Formula/emacs-mac.rb:4 https://github.com/railwaycat/homebrew-emacsmacport/issues/39
emacs-mac failed to build on 10.10.2 https://github.com/railwaycat/homebrew-emacsmacport/issues/17
Does emacs-24.5-mac-5.15 (or 5.14) build work on Mavericks ? (10.9.5) https://github.com/railwaycat/homebrew-emacsmacport/issues/49
README-mac and NEWS-mac files does not exist https://github.com/railwaycat/homebrew-emacsmacport/issues/9
/User/xinx/ specific compilation refs when running .../bin/emacs (from the Cask build) https://github.com/railwaycat/homebrew-emacsmacport/issues/58
Add --with-borderless for running in a borderless window https://github.com/railwaycat/homebrew-emacsmacport/pull/62
Yomamoto Mituharu has begun pushing to bitbucket https://github.com/railwaycat/homebrew-emacsmacport/issues/53
failed to clone official repo https://github.com/railwaycat/homebrew-emacsmacport/issues/38
Hardcoded charsets directory breaks command-line binaries https://github.com/railwaycat/homebrew-emacsmacport/issues/21
Symbol's function definition is void: record https://github.com/railwaycat/homebrew-emacsmacport/issues/107
brew cask audit fails https://github.com/railwaycat/homebrew-emacsmacport/issues/65
DEL not working https://github.com/railwaycat/homebrew-emacsmacport/issues/102
Clang compilation errors https://github.com/railwaycat/homebrew-emacsmacport/issues/42
Equivalent for `ns-hide-emacs`?  https://github.com/railwaycat/homebrew-emacsmacport/issues/105
Crash on return from screen lock https://github.com/railwaycat/homebrew-emacsmacport/issues/20
Suggestion: Have option to create and move Emacs alias to Applications https://github.com/railwaycat/homebrew-emacsmacport/issues/13
Installing latest org through elpa results in latex fragment preview feature regression https://github.com/railwaycat/homebrew-emacsmacport/issues/73
Fails to install on 10.10.4 with autogen.sh error https://github.com/railwaycat/homebrew-emacsmacport/issues/36
rm symlink for terminal use, recommend .app https://github.com/railwaycat/homebrew-emacsmacport/pull/11
"FairPlay decryption failed on binary" when running built app bundle https://github.com/railwaycat/homebrew-emacsmacport/issues/43
Permission issues? https://github.com/railwaycat/homebrew-emacsmacport/issues/56
Full screen not working with 10.11 El Capitan beta 2 https://github.com/railwaycat/homebrew-emacsmacport/issues/34
Error: undefined local variable or method `emacs_icons_project_icons https://github.com/railwaycat/homebrew-emacsmacport/issues/61
emacsclient not functioning correctly https://github.com/railwaycat/homebrew-emacsmacport/issues/52
`M-h` is swallowed by OS X https://github.com/railwaycat/homebrew-emacsmacport/issues/55
Instructions in readme refer to old repo name "emacsport" https://github.com/railwaycat/homebrew-emacsmacport/issues/86
Add flag to use the official icon https://github.com/railwaycat/homebrew-emacsmacport/issues/97
```

**Comment by ViktorHaag** [comment]
BTW -- downloading the tarball and stepping carefully through the build instructions in the RB formula _seems_ to work...

**Comment by ViktorHaag** [comment]
This problem still persists with:
- OSX 10.12.6
- xcode-select version: 2347, command line tools installed
- XCode 9.2 + Command Line Tools (macOS Sierra version 10.12) for Xcode, version 9.2 updated, as of Dec 12/2017

**Comment by railwaycat** [comment]
Hi @ViktorHaag, unfortunately I cannot reproduce your issue on my local, with the same OS and Xcode version. 

From Homebrew log, this error happened in `make` phase when building emacs mac port, at that time, everything should under `/private/tmp/` directory (if you didn't make any advanced change on macOS or Homebrew). This directory controlled by macOS and everyone have permission to read/write/execute. It's really wired to see a permission error here.

**Comment by ViktorHaag** [comment]
@railwaycat -- I am still having this issue with `emacs-mac` updates. I am beginning to suspect that, since it works on all my macs but my _work_ mac, that my IT department has done something to the configuration of my work mac that breaks this for some reason. If there's anything I can do from _this_ end to assist in further debugging of this situation, I am happy to do that. But I am now resigned to having to rebuild the emacs-mac recipe by hand every time I do an upgrade.

**Comment by railwaycat** [comment]
Hi, since it's been a while, both macOS and mac port has upgraded. I'm going to close this issue for now and welcome to open a new one or reopen this if you still see this issue on the latest version:)
