### ISSUE TITLE
Trying to build --HEAD fails with spurious gnutls error

### ISSUE THREAD

**Issue by mvarela** [railwaycat/homebrew-emacsmacport#114]
I'm trying to get the 26-pretest version up and running, and tried installing via homebrew (on Mac OS Sierra), but the build fails while running `configure`, with an error about `gnutls` not being present. Gnutls is, however, installed on the system. 

    ~/Devel/Sunburn-Theme on  master took 7s
    λ brew upgrade emacs-mac --HEAD -with-spacemacs-icon
    ==> Upgrading 1 outdated package, with result:
    railwaycat/emacsmacport/emacs-mac HEAD
    ==> Upgrading railwaycat/emacsmacport/emacs-mac
    ==> Cloning https://bitbucket.org/mituharu/emacs-mac.git
    Updating /Users/mvr/Library/Caches/Homebrew/emacs-mac--git
    ==> Checking out branch work
    ==> ./autogen.sh
    ==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/e
    Last 15 lines from /Users/mvr/Library/Logs/Homebrew/emacs-mac/02.configure:
    checking for LIBGNUTLS... no
    checking for LIBSYSTEMD... no
    checking sys/inotify.h usability... no
    checking sys/inotify.h presence... no
    checking for sys/inotify.h... no
    checking for KQUEUE... no
    checking for library containing kqueue... none required
    checking for library containing cmsCreateTransform... -llcms2
    checking for library containing inflateEnd... -lz
    configure: error: The following required libraries were not found:
         gnutls
    Maybe some development libraries/packages are missing?
    If you don't want to link with them give
         --with-gnutls=no
    as options to configure
    
    If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
    https://github.com/railwaycat/homebrew-emacsmacport/issues
    
    These open issues may also help:
    Emacs Mac port for 26.0.90 pretest https://github.com/railwaycat/homebrew-emacsmacport/issues/113
    Trouble installing emacs-25.3-mac-6.8 https://github.com/railwaycat/homebrew-emacsmacport/issues/109
    Trouble installing emacs-25.3-mac-6.7 https://github.com/railwaycat/homebrew-emacsmacport/issues/108
    Update to emacs-25.2-rc2-mac-6.2 https://github.com/railwaycat/homebrew-emacsmacport/pull/93
    Fullscreen on emacs-25.1-rc1-mac-5.90 https://github.com/railwaycat/homebrew-emacsmacport/issues/68
    Error: /Library/Caches/Homebrew/Formula/emacs-mac.rb:4 https://github.com/railwaycat/homebrew-emacsmacport/issues/39
    emacs-mac failed to build on 10.10.2 https://github.com/railwaycat/homebrew-emacsmacport/issues/17
    Install emacs-module.h when built with module support https://github.com/railwaycat/homebrew-emacsmacport/pull/112
    How to add --with-modules to system-configuration-options? https://github.com/railwaycat/homebrew-emacsmacport/issues/111
    /User/xinx/ specific compilation refs when running .../bin/emacs (from the Cask build) https://github.com/railwaycat/homebrew-emacsmacport/issues/58
    Hardcoded charsets directory breaks command-line binaries https://github.com/railwaycat/homebrew-emacsmacport/issues/21
    brew cask audit fails https://github.com/railwaycat/homebrew-emacsmacport/issues/65
    Symbol's function definition is void: record https://github.com/railwaycat/homebrew-emacsmacport/issues/107
    Clang compilation errors https://github.com/railwaycat/homebrew-emacsmacport/issues/42
    DEL not working https://github.com/railwaycat/homebrew-emacsmacport/issues/102
    Crash on return from screen lock https://github.com/railwaycat/homebrew-emacsmacport/issues/20
    Equivalent for `ns-hide-emacs`?  https://github.com/railwaycat/homebrew-emacsmacport/issues/105
    Suggestion: Have option to create and move Emacs alias to Applications https://github.com/railwaycat/homebrew-emacsmacport/issues/13
    Installing latest org through elpa results in latex fragment preview feature regression https://github.com/railwaycat/homebrew-emacsmacport/issues/73
    Fails to install on 10.10.4 with autogen.sh error https://github.com/railwaycat/homebrew-emacsmacport/issues/36
    rm symlink for terminal use, recommend .app https://github.com/railwaycat/homebrew-emacsmacport/pull/11
    "FairPlay decryption failed on binary" when running built app bundle https://github.com/railwaycat/homebrew-emacsmacport/issues/43
    Permission issues? https://github.com/railwaycat/homebrew-emacsmacport/issues/56
    Full screen not working with 10.11 El Capitan beta 2 https://github.com/railwaycat/homebrew-emacsmacport/issues/34
    Error: undefined local variable or method `emacs_icons_project_icons https://github.com/railwaycat/homebrew-emacsmacport/issues/61
    emacsclient not functioning correctly https://github.com/railwaycat/homebrew-emacsmacport/issues/52
    `M-h` is swallowed by OS X https://github.com/railwaycat/homebrew-emacsmacport/issues/55
    Instructions in readme refer to old repo name "emacsport" https://github.com/railwaycat/homebrew-emacsmacport/issues/86
    Add flag to use the official icon https://github.com/railwaycat/homebrew-emacsmacport/issues/97

If I run `brew upgrade gnutls`, I get:
 
    λ brew upgrade gnutls
     Updating Homebrew...
     ==> Auto-updated Homebrew!
     Updated 1 tap (homebrew/core).
     ==> Updated Formulae
     carthage                                           packer
    
    Error: gnutls 3.5.15 already installed

Any ideas on why this may be failing?

**Comment by railwaycat** [comment]
I think this because of gnutls been installed from hombrew not link it's libs and includes to `/usr/local` by default. 

Build with `--with-gnutls` should fix this. 

Currently `--with-gnutls` is an optional dependency for mac port, let me take a closer look..if it become a requirement from 26 then I have to make it as requirement in formula too.

**Comment by mvarela** [comment]
I edited the formula and added the --with-gnutls=no option to configure, and it built.
Regarding the gnutls stuff, both the dylib and the headers are linked by homebrew:

    λ ls -lah /usr/local/lib/libgnutls.30.dylib
    lrwxr-xr-x 1 mvr admin 46 Sep 18 23:08 /usr/local/lib/libgnutls.30.dylib -> ../Cellar/gnutls/3.5.15/lib/libgnutls.30.dylib

    λ ls -lah /usr/local/include/gnutls
    lrwxr-xr-x 1 mvr admin 38 Sep 18 23:08 /usr/local/include/gnutls -> ../Cellar/gnutls/3.5.15/include/gnutls

So maybe there's a problem somewhere else. 
Thanks again!

**Comment by mvarela** [comment]
By the way, I was checking the changelog for Emacs 26, and `gnutls` is now required:

    * Installation Changes in Emacs 26.1
    
    ** By default libgnutls is now required when building Emacs.
    Use 'configure --with-gnutls=no' to build even when GnuTLS is missing.
    
    ** GnuTLS version 2.12.2 or later is now required, instead of merely
    version 2.6.6 or later.

The build I just made without `gnutls` can't connect to MELPA, for instance.

**Comment by sjrmanning** [comment]
@mvarela I had the same problem, and as railwaycat mentioned above adding `--with-gnutls` actually fixes the whole problem.

Without `--with-gnutls` it doesn't find `libgnutls` installed from Homebrew (in `/usr/local/lib`), but explicitly building with gnutls support finds it correctly, resulting in a properly working HEAD build :)

**Comment by mvarela** [comment]
Thanks for reminding me try this again, now it worked (I also got an upgrade of gnutls, maybe that was an issue).
